### ISSUE TITLE
verbose argument ... is it for users or developers?

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/nwfscDiag#27]
@iantaylor-NOAA I have never thought of verbose as a tool for debugging. I always thought that it was messages for the user not messages for the developers. I think this is a design question that we should address in a different issue, maybe on PEPtools and then apply the outcome across all packages.

_Originally posted by @kellijohnson-NOAA in https://github.com/pfmc-assessments/nwfscDiag/pull/24#discussion_r1245750205_

**Comment by iantaylor-NOAA** [comment]
Copied from #24:
I was looking for more information as a user. I think there are times that your inputs are bad and with better message you can fix it rather than just email the package developers every time something doesn't work right away. For sure the message in question here is not valuable, but I think other places would be (e.g. https://github.com/pfmc-assessments/nwfscDiag/issues/28).

I just glanced at https://github.com/r4ss/r4ss/issues/79 which includes a discussion about what gets printed to the screen by {r4ss} (and also reminds me of first learning about the `message()` function in 2015). I think that I'm overdue for some education in current best practices for user feedback from R packages, including the use of [{cli}](https://cli.r-lib.org/index.html) as in {PacFIN.Utilities}.
