### ISSUE TITLE
dplyr::vars deprecated and needs to be replaced

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [pfmc-assessments/nwfscDiag#39]
`plot_retro()` uses `dplyr::mutate_at` and `dplyr::vars` to calculate percent difference across models where each model in the retrospective is a column.  The `dplyr::vars` function appears to be deprecated:

```
Warning message:
Using an external vector in selections was deprecated in tidyselect 1.1.0.
ℹ Please use `all_of()` or `any_of()` instead.
  # Was:
  data %>% select(denom)

  # Now:
  data %>% select(all_of(denom))

See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
```
The `dplyr::vars` function is used [here](https://github.com/pfmc-assessments/nwfscDiag/blob/3da8fbf80cd1c02bc457b361e364b2d20b39a7d7/R/plot_retro.R#L128) for the first time. I have tried replacing `mutate_at` to `mutate` and `vars` to `select`; however, these changes do not calculate the percent difference across model columns.  I am a bit stuck on how best to fix this issue.  @kellijohnson-NOAA Ideas?

**Comment by chantelwetzel-noaa** [comment]
I tried that combination abut it yields this:

````
> retroSummary$SpawnBio %>%
+     dplyr::filter(Yr %in% years) %>%
+     dplyr::mutate(dplyr::across(denom), list(per_diff = ~100*./model1 - 100))
     model1   model2   model3    Label   Yr list(per_diff = ~100 * ./model1 - 100)
1  24096.10 23037.90 22932.50 SSB_2012 2012                  ~100 * ./model1 - 100
2  22126.10 20983.50 20851.70 SSB_2013 2013                  ~100 * ./model1 - 100
```

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa try this, note that I have not tried it with an actual example so we might need to debug it some but all of the concepts are there. Note that I changed to using `[["SpawnBio"]]` rather than the $ which is ☹️ upon because it allows for partial matching. I also changed to the native pipe rather than magrittr, this change causes the "." notation in your original code to not work, which is why I use an anonymous function, i.e., `\(x)`. Happy to jump on a chat before 10 am to explain anything. One more also, if you want to really 🤯 we can do all of this with a call to purrr so you do not have to repeat code for every list item in `retroSummary`.
```
  sb <- retroSummary[["SpawnBio"]] |>
    dplyr::filter(Yr %in% years) |>
    dplyr::mutate(dplyr::across(
      # Finds the columns that match "model1", "model2", ...
      .cols = dplyr::matches("model[0-9]+$"),
      # model1 is the reference for all model comparisons
      .fns = \(x) 100 * x / model1 - 100,
      # renames the output columns per_diff_model1, per_diff_model2, ...
      .names = "per_diff_{.col}"
    ))
```

**Comment by chantelwetzel-noaa** [comment]
I have been switching to ``[["parameter name"]]` and `|>` as I update and change things but have not put in the effort to change it everywhere yet.  This fix appears to work.  I will move to this new approach and confirm everything still works correctly.  Thank you.
